// Contract tests with simulated TTS events. These do not assess audible voice quality.
const fs=require('fs'),assert=require('node:assert/strict'),{JSDOM,VirtualConsole}=require('jsdom');
const input=process.argv[2]||'app/src/main/assets/index.html';let source=fs.readFileSync(input,'utf8');
source=source.replace('    initSegments();bind();',`window.__speech={speak,stopSpeech,normalizeSpeechText,splitSpeechText,localVoices,structureNarration,TA_INTROS,STRUCTURES,PROCEDURE_STEPS,handleNativeMessage,renderAll,openProcedure,toggleProcedurePlay,closeProcedure,getJob:()=>speechJob,getDemo:()=>demo,getState:()=>state,setState:x=>{state=normalizeState(x)}};\n    initSegments();bind();`);
let finished=false;process.on("beforeExit",()=>{if(!finished){console.error("Unresolved test at check",checks);process.exitCode=1}});let checks=0;const ok=(condition,message)=>{assert.ok(condition,message);checks++};
function setup(native=false){let now=0,id=0,timers=new Map(),spoken=[],messages=[],listeners={},voiceList=[{name:'English',voiceURI:'en',lang:'en-IN',localService:true},{name:'Tamil network',voiceURI:'net',lang:'ta-IN',localService:false},{name:'Tamil local',voiceURI:'ta-local',lang:'ta-IN',localService:true},{name:'Other Tamil',voiceURI:'ta-other',lang:'ta-LK',localService:true,default:true}];const errors=[],log=new VirtualConsole();log.on('jsdomError',e=>errors.push(e.message));
const dom=new JSDOM(source,{url:'https://appassets.androidplatform.net/assets/index.html',runScripts:'dangerously',pretendToBeVisual:true,virtualConsole:log,beforeParse(w){w.HTMLElement.prototype.scrollIntoView=()=>{};w.matchMedia=()=>({matches:true});w.Date.now=()=>now;w.setTimeout=(f,ms=0)=>{timers.set(++id,{at:now+ms,f});return id};w.clearTimeout=i=>timers.delete(i);w.localStorage.setItem('earthwormDissection.v1',JSON.stringify({lang:'ta',sound:false,voice:true}));w.SpeechSynthesisUtterance=class{constructor(text){this.text=text}};w.speechSynthesis={getVoices:()=>voiceList,addEventListener:(k,f)=>listeners[k]=f,speak:u=>spoken.push(u),cancel:()=>{}};if(native)w.EarthwormNative={postMessage:s=>messages.push(JSON.parse(s))}}});
return {w:dom.window,t:dom.window.__speech,spoken,messages,errors,setVoices:v=>{voiceList=v;listeners.voiceschanged?.()},async tick(ms){const end=now+ms;for(let n=0;n<10000;n++){const next=[...timers].filter(([,x])=>x.at<=end).sort((a,b)=>a[1].at-b[1].at)[0];if(!next)break;timers.delete(next[0]);now=next[1].at;next[1].f();await Promise.resolve()}now=end;await Promise.resolve()},close:()=>dom.window.close()}}
(async()=>{
const c=setup(),t=c.t;
ok(t.normalizeSpeechText('XIV–XVI கண்டங்கள். O₂-ஐ CO₂-ஐ S வடிவ','ta')==='பதினான்காம் முதல் பதினாறாம் கண்டங்கள். ஆக்சிஜனை கார்பன் டைஆக்சைடை எஸ் வடிவ','Spoken notation expands without changing scientific labels');
ok(t.normalizeSpeechText('VIII-ஆம் கண்டம்','ta')==='எட்டாம் கண்டம்','Ordinal suffix is not doubled');
ok(t.normalizeSpeechText('மண்\u200Bபுழு <b>உடல்</b>','ta')==='மண்புழு உடல்','Hidden spacing and HTML removed');
ok(t.localVoices()[0].voiceURI==='ta-local','Exact local Tamil locale preferred');ok(!t.localVoices().some(v=>v.voiceURI==='net'),'Network voice excluded');
for(const id of Object.keys(t.STRUCTURES)){ok(t.TA_INTROS[id],'Reviewed introduction for '+id);const text=t.normalizeSpeechText(t.structureNarration(id),'ta');ok(!/\b[IVX]+\b|O₂|CO₂/.test(text),'No raw notation in narration '+id);ok(text===text.normalize('NFC'),'Normalized Tamil '+id)}
for(const step of t.PROCEDURE_STEPS)for(const chunk of t.splitSpeechText(step.ta)){ok(chunk.length<=240,'Procedure chunk remains within engine limit');ok(!/^[\u0BBE-\u0BCD]/.test(chunk),'Chunk does not begin with detached vowel sign')}
let done=t.speak('முதல் வாக்கியம். இரண்டாவது வாக்கியம்.');ok(c.spoken.at(-1).text==='முதல் வாக்கியம்.','Starts one sentence');const first=c.spoken.at(-1);first.onend();await c.tick(160);ok(c.spoken.at(-1).text==='இரண்டாவது வாக்கியம்.','Next sentence follows completion');c.spoken.at(-1).onend();ok(await done==='ended','Completion resolves at final sentence');
done=t.speak('முதல் வாக்கியம். இரண்டாவது வாக்கியம்.');const stale=c.spoken.at(-1),count=c.spoken.length;t.stopSpeech();stale.onend();await c.tick(1000);ok(await done==='cancelled','Stop resolves cancellation');ok(c.spoken.length===count,'Stale callback cannot restart playback');
c.setVoices([]);done=t.speak('மண்புழு.');await c.tick(1201);ok(await done==='error','Missing voice resolves failure');ok(c.w.document.querySelector('#voiceWarning').classList.contains('show'),'Missing voice explanation shown');
done=t.speak('மண்புழு.');c.setVoices([{name:'Late Tamil',voiceURI:'late',lang:'ta-IN',localService:true}]);ok(c.spoken.at(-1).voice.voiceURI==='late','Late voice discovery resumes queued request');c.spoken.at(-1).onend();ok(await done==='ended','Late voice completes');
t.openProcedure();t.toggleProcedurePlay();await c.tick(7000);ok(t.getDemo().index===0,'Long Tamil speech is not cut at 5.2 seconds');
for(let i=0;t.getJob()&&i<20;i++){c.spoken.at(-1).onend();await c.tick(160)}await c.tick(650);ok(t.getDemo().index===1,'Demonstration advances after full narration');
t.toggleProcedurePlay();const paused=t.getDemo().index;await c.tick(60000);ok(t.getDemo().index===paused&&!t.getDemo().playing,'Pause stops narration and automatic advance');t.closeProcedure();
t.setState({lang:'ta',voice:false,sound:false});t.renderAll();t.openProcedure();t.toggleProcedurePlay();await c.tick(1);
ok(t.getDemo().playing,'Silent demonstration starts');const nativePaused=t.getDemo().index;c.w.EarthwormApp.pause();await c.tick(12000);
ok(!t.getDemo().playing&&t.getDemo().index===nativePaused,'Native pause cancels silent procedure timer');
t.toggleProcedurePlay();const hiddenAt=t.getDemo().index;c.w.dispatchEvent(new c.w.Event('pagehide'));await c.tick(12000);
ok(!t.getDemo().playing&&t.getDemo().index===hiddenAt,'Page hide cancels pending procedure advance');t.closeProcedure();
t.setState({lang:'ta',voice:true,sound:false});t.renderAll();
done=t.speak('மண்புழு.');c.spoken.at(-1).onerror({error:'synthesis-failed'});ok(await done==='error','Engine failure resolves');
done=t.speak('மண்புழு.');await c.tick(30000);ok(await done==='error','Missing completion times out safely');
ok(c.errors.length===0,'No DOM errors '+c.errors.join(';'));c.close();
const n=setup(true),nt=n.t;nt.handleNativeMessage({data:JSON.stringify({type:'voices',voices:[{name:'Tamil local',voiceURI:'native-ta',lang:'ta-IN',localService:true,quality:400}]})});done=nt.speak('முதல் வாக்கியம். அடுத்த வாக்கியம்.');let msg=n.messages.filter(m=>m.type==='speak').at(-1);ok(msg.voice==='native-ta','Native voice identity sent');ok(msg.lang==='ta-IN','Native Tamil locale explicit');nt.handleNativeMessage({data:JSON.stringify({type:'voice-ended',id:'stale-id'})});ok(nt.getJob().index===0,'Stale native event rejected');nt.handleNativeMessage({data:JSON.stringify({type:'voice-ready',id:msg.id})});ok(nt.getJob().index===0,'Ready is not mistaken for completion');nt.handleNativeMessage({data:JSON.stringify({type:'voice-ended',id:msg.id})});await n.tick(160);msg=n.messages.filter(m=>m.type==='speak').at(-1);ok(msg.text==='அடுத்த வாக்கியம்.','Native sentence advances on ended');nt.handleNativeMessage({data:JSON.stringify({type:'voice-ended',id:msg.id})});ok(await done==='ended','Native narration resolves');
done=nt.speak('மண்புழு.');msg=n.messages.filter(m=>m.type==='speak').at(-1);nt.handleNativeMessage({data:JSON.stringify({type:'voice-error',id:msg.id})});ok(await done==='error','Native error is handled');
done=nt.speak('மண்புழு.');msg=n.messages.filter(m=>m.type==='speak').at(-1);nt.handleNativeMessage({data:JSON.stringify({type:'voice-cancelled',id:'stale-id'})});ok(nt.getJob()!==null,'Stale native cancellation ignored');
nt.handleNativeMessage({data:JSON.stringify({type:'voice-cancelled',id:msg.id})});ok(await done==='cancelled','Native interruption resolves without a watchdog timeout');ok(nt.getJob()===null,'Native interruption clears the speech job');n.close();
const report={date:new Date().toISOString().slice(0,10),htmlSHA256:require('node:crypto').createHash('sha256').update(fs.readFileSync(input)).digest('hex'),checks,errors:[],scope:'Tamil text and narration event contracts with mocked browser/native speech. No audio or device execution.'};fs.writeFileSync('tests/tamil-voice-results.json',JSON.stringify(report,null,2));finished=true;console.log(report);
})().catch(e=>{console.error(e);process.exitCode=1});
